
/*
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by Ahmed shaban
 * @brief          : Main program body

 ******************************************************************************
 */
#include <stdint.h>
//RCC register to enable clock
#define RCC_BASE  0x40021000
#define RCC_APB2ENR *(volatile uint32_t* ) (RCC_BASE+0X18)
#define RCC_IOPAEN (1<<2)
//gpio enable
#define GPIO_BAES 0x40010800
#define GPIOA_CRH    *(volatile uint32_t* ) (GPIO_BAES +0X04)
#define GPIOA_ORD    *(volatile uint32_t* ) (GPIO_BAES +0X0c)
#define GPIOA_CEL    *(volatile uint32_t* ) (GPIO_BAES +0X00) //outpot pin

#define GPIO13     (1UL<<13)
//Etern interrput preipheler enable
#define EXTI_BAES    0x40010400
#define EXTI_IMR     *(volatile uint32_t*) (EXTI_BAES +0X00) //Interrupt mask register
#define EXTI_RTSR    *(volatile uint32_t*) (EXTI_BAES +0X08) //Rising trigger selection register
#define EXTI_PR      *(volatile uint32_t*) (EXTI_BAES +0X14) //panding selection register


#define AFIO_BAES    0x40010000
#define AFIO_EXTICR1   *(volatile uint32_t*) (AFIO_BAES +0X08)
#define  RCC_BAES    0x40021000
#define RCC_APB2RSTR   *(volatile uint32_t*) (RCC_BAES +0X0c)

//AFIO

#define NVIC_EXTTE0   *(volatile uint32_t*) (0xE000E100)


void clock_init()
{//clock_init
	RCC_APB2ENR |=RCC_IOPAEN ;
	//enable clock for eternal interrup
	RCC_APB2RSTR |= (1<<0); //eternal interrup

}
void gpio_init()
{
	//pin 13 portA output
	GPIOA_CRH &=0xFF0FFFFF ;
	GPIOA_CRH |=0x00200000 ;
	GPIOA_CEL |= (1<<2);
}

int main(void)
{


	gpio_init();
	clock_init();

		//enable mask register line 0
		EXTI_IMR |=(1<<0) ;
		//Rising trigger selection register line 0
		EXTI_RTSR |=(1<<0) ;
		//clear panding register for line 0
		EXTI_PR |=(1<<0);
		AFIO_EXTICR1 =0;
		//enable NVIC
		NVIC_EXTTE0 |=1<<6;
		while (1);

	}
	void EXTI0_IRQHandler()
	{
		//interrput is happen
		//pin A13 toggle
		GPIOA_ORD ^=(1<<13);
	}


