/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by Ahmed shaban
 * @brief          : Main program body
 
 *
 ******************************************************************************
 */
#include <stdint.h>
#define RCC_BASE 0x40021000
#define GPIO_BAES 0x40010800
#define RCC_APB2ENR *(volatile uint32_t* ) (RCC_BASE+0X18)
#define GPIOA_CRH   *(volatile uint32_t* ) (GPIO_BAES +0X04)
#define GPIOA_ORD   *(volatile uint32_t* ) (GPIO_BAES +0X0c)
#define RCC_IOPAEN (1<<2)
#define GPIO13     (1UL<<13)
 extern void NMI_Handler(void)
{
	
}
 extern void Bus_fault(void)
 {
	 
	 
 }
typedef union {
uint32_t   all;
struct{
uint32_t rev:13;
uint32_t p_13:1;
}pin;
} R_ODR_t;
volatile R_ODR_t* R_ODR =  (volatile R_ODR_t* )(GPIO_BAES +0X0C);

int main(void)
{
	RCC_APB2ENR |=RCC_IOPAEN ;
	GPIOA_CRH &=0xFF0FFFFF ;
	GPIOA_CRH |=0x00200000 ;
	while(1)
	{
		R_ODR->pin.p_13 =1;
		for( int i=0 ;i<5000;i++);
		R_ODR->pin.p_13 =0;
		for( int i=0 ;i<5000;i++) ;
	}

}

